### ISSUE TITLE
reuse CLI libraries to create rclone ente backend

### ISSUE THREAD

**Issue by im7mortal** [ente-io/cli#4] opened 2023-10-21 14:49 UTC
ente-io/ente#615

It would be pretty practical we could reuse CLI libraries to create rclone ente backend.

**Comment by ua741** [comment] 2023-10-23 04:44
Thank you for creating this issue.

Our current focus is on improving support for export via ente-cli. Given that photos within ente don't directly map to a standard file system and everything is end-to-end encrypted (e2ee), developing r-clone backend integration will introduce certain overheads.

Importing photos requires generating thumbnails, parsing EXIF data, and performing several other client-side actions, such as grouping live photos.

We plan to support exporting photos to an S3-compliant API. Instead of exporting multiple copies of photos based on the albums they belong to, we aim to export just one copy. The associated metadata will include information about the respective albums.

That said, we would be more than happy to accept community contributions if anyone decides to build an rclone backend for export.

**Comment by mnvr** [comment] 2024-03-03 08:16
Closing this as a duplicate of https://github.com/ente-io/ente/discussions/616 (also commenting here to cross-ref).

**Closed by mnvr** 2024-03-03 08:16 UTC
Labels: help wanted
